/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaspbo;

import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author MSI
 */
public class PengaturanJam extends javax.swing.JFrame {

    
   

    public PengaturanJam() {
        initComponents();
        
         // Add ActionListener for jButton1 (tombol "Change")
        Ubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ubah1ActionPerformed(evt);
            }
        });
        
        Ubah2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Ubah2ActionPerformed(evt);
        }
    });
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TargetJamKerja = new javax.swing.JLabel();
        inputTarget = new javax.swing.JTextField();
        Edit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tujuan1 = new javax.swing.JLabel();
        Ubah1 = new javax.swing.JButton();
        Tujuan2 = new javax.swing.JLabel();
        Ubah2 = new javax.swing.JButton();
        PilWaktu1 = new javax.swing.JTextField();
        PilWaktu2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(232, 232, 246));

        TargetJamKerja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TargetJamKerja.setText("Target Jam Kerja : ");

        inputTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTargetActionPerformed(evt);
            }
        });

        Edit.setBackground(new java.awt.Color(240, 194, 55));
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("My Productivity Tracker");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productivity.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(367, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Tujuan1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tujuan1.setText(" Tujuan :");

        Ubah1.setBackground(new java.awt.Color(240, 194, 55));
        Ubah1.setText("Ubah");
        Ubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ubah1ActionPerformed(evt);
            }
        });

        Tujuan2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Tujuan2.setText(" Tujuan :");

        Ubah2.setBackground(new java.awt.Color(240, 194, 55));
        Ubah2.setText("Ubah");
        Ubah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ubah2ActionPerformed(evt);
            }
        });

        PilWaktu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilWaktu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Tujuan2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(TargetJamKerja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tujuan1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PilWaktu1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(Ubah1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PilWaktu2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Ubah2)))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tujuan1)
                    .addComponent(Ubah1)
                    .addComponent(PilWaktu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TargetJamKerja, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tujuan2)
                    .addComponent(Ubah2)
                    .addComponent(PilWaktu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    
    private void inputTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTargetActionPerformed
       try {
            int newTargetHours = Integer.parseInt(inputTarget.getText());
            if (newTargetHours >= 0) {
                JOptionPane.showMessageDialog(this, "Target set to " + newTargetHours + " hours.");
            } else {
                JOptionPane.showMessageDialog(this, "Masukkan angka yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_inputTargetActionPerformed
    
    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
      String newTargetHoursString = JOptionPane.showInputDialog(this, "Masukkan jam kerja baru:", "Edit Jam Kerja", JOptionPane.PLAIN_MESSAGE);
        try {
            int newTargetHours = Integer.parseInt(newTargetHoursString);
            if (newTargetHours >= 0) {
                inputTarget.setText(String.valueOf(newTargetHours));
                JOptionPane.showMessageDialog(this, "Target set to " + newTargetHours + " hours.");
            } else {
                JOptionPane.showMessageDialog(this, "Masukkan angka yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid.", "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }
     

private String getTextFromTextField(JTextField textField) {
    return textField.getText();
}

private Object[] getComboBoxItems() {
    String text = getTextFromTextField(PilWaktu1);
    return new Object[]{text};
    
    }//GEN-LAST:event_EditActionPerformed

    private void Ubah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ubah1ActionPerformed
    String selectedTime = (String) JOptionPane.showInputDialog(
            this,
            "Pilih waktu:",
            "Pilih Waktu",
            JOptionPane.PLAIN_MESSAGE,
            null,
            null,
            PilWaktu1.getText());

    if (selectedTime != null) {
        PilWaktu1.setText(selectedTime);
        JOptionPane.showMessageDialog(this, "Waktu dipilih: " + selectedTime, "Pilih Waktu", JOptionPane.INFORMATION_MESSAGE);
    }   
    }//GEN-LAST:event_Ubah1ActionPerformed

    private void PilWaktu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilWaktu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PilWaktu1ActionPerformed

    private void Ubah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ubah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ubah2ActionPerformed

    private void Change2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
    String selectedTime = (String) JOptionPane.showInputDialog(
        this,
        "Pilih waktu:",
        "Pilih Waktu",
        JOptionPane.PLAIN_MESSAGE,
        null,
        null,
        PilWaktu2.getText());

if (selectedTime != null) {
    PilWaktu2.setText(selectedTime);
    JOptionPane.showMessageDialog(this, "Waktu dipilih: " + selectedTime, "Pilih Waktu", JOptionPane.INFORMATION_MESSAGE);
} 
    }
    
    // Method to update worked hours display
    private void updateWorkedHoursDisplay() {
        
    }

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengaturanJam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengaturanJam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PengaturanJam().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JTextField PilWaktu1;
    private javax.swing.JTextField PilWaktu2;
    private javax.swing.JLabel TargetJamKerja;
    private javax.swing.JLabel Tujuan1;
    private javax.swing.JLabel Tujuan2;
    private javax.swing.JButton Ubah1;
    private javax.swing.JButton Ubah2;
    private javax.swing.JTextField inputTarget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    
}
